protected/modules/question/models/Question.php
<?php

/**
 * This is the model class for table "{{question}}".
 *
 * The followings are the available columns in table '{{question}}':
 * @property integer $id
 * @property integer $theme_id
 * @property string $text
 * @property string $option1
 * @property string $option2
 * @property string $option3
 * @property string $option4
 * @property integer $answer
 * @property string $explanation
 *
 * @property QuestionTheme $theme
 */
class Question extends YModel
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{question}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('theme_id, text, option1, option2, option3, option4, answer', 'required'),
			array('theme_id, answer', 'numerical', 'integerOnly' => true),
			array('text, option1, option2, option3, option4, explanation', 'safe'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, theme_id, text, option1, option2, option3, option4, answer, explanation', 'safe', 'on' => 'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'theme' => array(self::BELONGS_TO, 'QuestionTheme', 'theme_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id'          => 'ID',
			'theme_id'    => 'Тема вопроса',
			'text'        => 'Текст вопроса',
			'option1'     => 'Вариант A',
			'option2'     => 'Вариант B',
			'option3'     => 'Вариант C',
			'option4'     => 'Вариант D',
			'answer'      => 'Ответ',
			'explanation' => 'Объяснение',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('theme_id', $this->theme_id);
		$criteria->compare('text', $this->text, true);
		$criteria->compare('option1', $this->option1, true);
		$criteria->compare('option2', $this->option2, true);
		$criteria->compare('option3', $this->option3, true);
		$criteria->compare('option4', $this->option4, true);
		$criteria->compare('answer', $this->answer);
		$criteria->compare('explanation', $this->explanation, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Question the static model class
	 */
	public static function model($className = __CLASS__)
	{
		return parent::model($className);
	}

	public function getAnswerList()
	{
		return array(
			1 => 'A',
			2 => 'B',
			3 => 'C',
			4 => 'D',
		);
	}

	public function getAnswers()
	{
		return array(
			1 => 'A. ' . $this->option1,
			2 => 'B. ' . $this->option2,
			3 => 'C. ' . $this->option3,
			4 => 'D. ' . $this->option4,
		);
	}

	public function getAnswerName()
	{
		$data = $this->getAnswerList();

		return isset($data[$this->answer]) ? $data[$this->answer] : Yii::t('QuestionModule.question', '*неизвестно*');
	}

	public function getThemeName()
	{
		return (isset($this->theme)) ? $this->theme->name : false;
	}
}

protected/modules/question/controllers/DefaultController.php
<?php
/**
 * Класс QuestionController:
 *
 *   @category YupeYBackController
 *   @package  YupeCMS
 *   @author   Yupe Team <team@yupe.ru>
 *   @license  https://github.com/yupe/yupe/blob/master/LICENSE BSD
 *   @link     http://yupe.ru
 **/
class DefaultController extends YBackController
{
    /**
     * Отображает вопрос по указанному идентификатору
     *
     * @param integer $id Идинтификатор вопрос для отображения
     *
     * @return nothing
     */
    public function actionView($id)
    {
        $this->render('view', array('model' => $this->loadModel($id)));
    }

    /**
     * Создает новую модель вопроса.
     * Если создание прошло успешно - перенаправляет на просмотр.
     *
     * @return nothing
     */
    public function actionCreate()
    {
        $model = new Question;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Question'])) {
            $model->attributes = $_POST['Question'];

            if ($model->save()) {
                Yii::app()->user->setFlash(
                    YFlashMessages::SUCCESS_MESSAGE,
                    Yii::t('question', 'Запись добавлена!')
                );

                if (!isset($_POST['submit-type']))
                    $this->redirect(array('update', 'id' => $model->id));
                else
                    $this->redirect(array($_POST['submit-type']));
            }
        }
        $this->render('create', array('model' => $model));
    }

    /**
     * Редактирование вопроса.
     *
     * @param integer $id Идинтификатор вопрос для редактирования
     *
     * @return nothing
     */
    public function actionUpdate($id)
    {
        $model = $this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Question'])) {
            $model->attributes = $_POST['Question'];

            if ($model->save()) {
                Yii::app()->user->setFlash(
                    YFlashMessages::SUCCESS_MESSAGE,
                    Yii::t('question', 'Запись обновлена!')
                );

                if (!isset($_POST['submit-type']))
                    $this->redirect(array('update', 'id' => $model->id));
                else
                    $this->redirect(array($_POST['submit-type']));
            }
        }
        $this->render('update', array('model' => $model));
    }

    /**
     * Удаляет модель вопроса из базы.
     * Если удаление прошло успешно - возвращется в index
     *
     * @param integer $id идентификатор вопроса, который нужно удалить
     *
     * @return nothing
     */
    public function actionDelete($id)
    {
        if (Yii::app()->request->isPostRequest)
        {
            // поддерживаем удаление только из POST-запроса
            $this->loadModel($id)->delete();

            Yii::app()->user->setFlash(
                YFlashMessages::NOTICE_MESSAGE,
                Yii::t('question', 'Запись удалена!')
            );

            // если это AJAX запрос ( кликнули удаление в админском grid view), мы не должны никуда редиректить
            if (!isset($_GET['ajax']))
                $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
        }
        else
            throw new CHttpException(400, Yii::t('question', 'Неверный запрос. Пожалуйста, больше не повторяйте такие запросы'));
    }

    /**
     * Управление вопросами.
     *
     * @return nothing
     */
    public function actionIndex()
    {
        $model = new Question('search');
        $model->unsetAttributes(); // clear any default values
        if (isset($_GET['Question']))
            $model->attributes = $_GET['Question'];
        $this->render('index', array('model' => $model));
    }

    /**
     * Возвращает модель по указанному идентификатору
     * Если модель не будет найдена - возникнет HTTP-исключение.
     *
     * @param integer идентификатор нужной модели
     *
     * @return nothing
     */
    public function loadModel($id)
    {
        $model = Question::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, Yii::t('question', 'Запрошенная страница не найдена.'));
        return $model;
    }

    /**
     * Производит AJAX-валидацию
     *
     * @param CModel модель, которую необходимо валидировать
     *
     * @return nothing
     */
    protected function performAjaxValidation($model)
    {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'question-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }
}

protected/modules/question/views/default/_form.php
<?php
/**
 * Отображение для _form:
 *
 * @category YupeView
 * @package  YupeCMS
 * @author   Yupe Team <team@yupe.ru>
 * @license  https://github.com/yupe/yupe/blob/master/LICENSE BSD
 * @link     http://yupe.ru
 **/
$form = $this->beginWidget(
	'bootstrap.widgets.TbActiveForm', array(
		'id'                     => 'question-form',
		'enableAjaxValidation'   => false,
		'enableClientValidation' => true,
		'type'                   => 'vertical',
		'htmlOptions'            => array('class' => 'well'),
		'inlineErrors'           => true,
	)
);
?>

	<div class="alert alert-info">
		<?php echo Yii::t('question', 'Поля, отмеченные'); ?>
		<span class="required">*</span>
		<?php echo Yii::t('question', 'обязательны.'); ?>
	</div>

<?php echo $form->errorSummary($model); ?>

	<div class="row-fluid control-group <?php echo $model->hasErrors('theme_id') ? 'error' : ''; ?>">
		<?php echo $form->dropDownListRow($model, 'theme_id', CHtml::listData($this->module->getThemeList(), 'id', 'name'), array('empty' => Yii::t('QuestionModule.question', '--выберите--'), 'class' => 'span5 popover-help', 'data-original-title' => $model->getAttributeLabel('theme_id'), 'data-content' => $model->getAttributeDescription('theme_id'))); ?>
	</div>
	<div class="row-fluid control-group <?php echo $model->hasErrors('text') ? 'error' : ''; ?>">
		<div class="popover-help" data-original-title='<?php echo $model->getAttributeLabel('text'); ?>' data-content='<?php echo $model->getAttributeDescription('text'); ?>'>
			<?php echo $form->labelEx($model, 'text'); ?>
			<?php
			$this->widget(
				$this->module->editor, array(
					'model'     => $model,
					'attribute' => 'text',
					'options'   => $this->module->editorOptions,
				)
			); ?>
		</div>
	</div>
	<div class="row-fluid control-group <?php echo $model->hasErrors('option1') ? 'error' : ''; ?>">
		<?php echo $form->textAreaRow($model, 'option1', array('class' => 'span5 popover-help', 'rows' => 6, 'cols' => 50, 'data-original-title' => $model->getAttributeLabel('option1'), 'data-content' => $model->getAttributeDescription('option1'))); ?>
	</div>
	<div class="row-fluid control-group <?php echo $model->hasErrors('option2') ? 'error' : ''; ?>">
		<?php echo $form->textAreaRow($model, 'option2', array('class' => 'span5 popover-help', 'rows' => 6, 'cols' => 50, 'data-original-title' => $model->getAttributeLabel('option2'), 'data-content' => $model->getAttributeDescription('option2'))); ?>
	</div>
	<div class="row-fluid control-group <?php echo $model->hasErrors('option3') ? 'error' : ''; ?>">
		<?php echo $form->textAreaRow($model, 'option3', array('class' => 'span5 popover-help', 'rows' => 6, 'cols' => 50, 'data-original-title' => $model->getAttributeLabel('option3'), 'data-content' => $model->getAttributeDescription('option3'))); ?>
	</div>
	<div class="row-fluid control-group <?php echo $model->hasErrors('option4') ? 'error' : ''; ?>">
		<?php echo $form->textAreaRow($model, 'option4', array('class' => 'span5 popover-help', 'rows' => 6, 'cols' => 50, 'data-original-title' => $model->getAttributeLabel('option4'), 'data-content' => $model->getAttributeDescription('option4'))); ?>
	</div>
	<div class="row-fluid control-group <?php echo $model->hasErrors('answer') ? 'error' : ''; ?>">
		<?php echo $form->dropDownListRow($model, 'answer', $model->answerList, array('class' => 'span3')); ?>
	</div>
	<div class="row-fluid control-group <?php echo $model->hasErrors('explanation') ? 'error' : ''; ?>">
		<?php echo $form->textAreaRow($model, 'explanation', array('class' => 'span5 popover-help', 'rows' => 6, 'cols' => 50, 'data-original-title' => $model->getAttributeLabel('explanation'), 'data-content' => $model->getAttributeDescription('explanation'))); ?>
	</div>

<?php
$this->widget(
	'bootstrap.widgets.TbButton', array(
		'buttonType' => 'submit',
		'type'       => 'primary',
		'label'      => Yii::t('question', 'Сохранить вопрос и закрыть'),
	)
); ?>
<?php
$this->widget(
	'bootstrap.widgets.TbButton', array(
		'buttonType'  => 'submit',
		'htmlOptions' => array('name' => 'submit-type', 'value' => 'index'),
		'label'       => Yii::t('question', 'Сохранить вопрос и продолжить'),
	)
); ?>

<?php $this->endWidget(); ?>

protected/modules/question/views/default/_search.php
<?php
/**
 * Отображение для _search:
 *
 *   @category YupeView
 *   @package  YupeCMS
 *   @author   Yupe Team <team@yupe.ru>
 *   @license  https://github.com/yupe/yupe/blob/master/LICENSE BSD
 *   @link     http://yupe.ru
 **/
$form = $this->beginWidget(
    'bootstrap.widgets.TbActiveForm', array(
        'action'      => Yii::app()->createUrl($this->route),
        'method'      => 'get',
        'type'        => 'vertical',
        'htmlOptions' => array('class' => 'well'),
    )
);
?>

    <fieldset class="inline">
        <div class="row-fluid control-group">
            <div class="span2">
                <?php echo $form->textFieldRow($model, 'id', array('class' => 'span3 popover-help', 'size' => 60, 'maxlength' => 60, 'data-original-title' => $model->getAttributeLabel('id'), 'data-content' => $model->getAttributeDescription('id'))); ?>
            </div>
            <div class="span2">
                <?php echo $form->textFieldRow($model, 'theme_id', array('class' => 'span3 popover-help', 'size' => 60, 'maxlength' => 60, 'data-original-title' => $model->getAttributeLabel('theme_id'), 'data-content' => $model->getAttributeDescription('theme_id'))); ?>
            </div>
            <div class="span2">
                <?php echo $form->textAreaRow($model, 'text', array('class' => 'span5 popover-help', 'rows' => 6, 'cols' => 50, 'data-original-title' => $model->getAttributeLabel('text'), 'data-content' => $model->getAttributeDescription('text'))); ?>
            </div>
            <div class="span2">
                <?php echo $form->textAreaRow($model, 'option1', array('class' => 'span5 popover-help', 'rows' => 6, 'cols' => 50, 'data-original-title' => $model->getAttributeLabel('option1'), 'data-content' => $model->getAttributeDescription('option1'))); ?>
            </div>
            <div class="span2">
                <?php echo $form->textAreaRow($model, 'option2', array('class' => 'span5 popover-help', 'rows' => 6, 'cols' => 50, 'data-original-title' => $model->getAttributeLabel('option2'), 'data-content' => $model->getAttributeDescription('option2'))); ?>
            </div>
            <div class="span2">
                <?php echo $form->textAreaRow($model, 'option3', array('class' => 'span5 popover-help', 'rows' => 6, 'cols' => 50, 'data-original-title' => $model->getAttributeLabel('option3'), 'data-content' => $model->getAttributeDescription('option3'))); ?>
            </div>
            <div class="span2">
                <?php echo $form->textAreaRow($model, 'option4', array('class' => 'span5 popover-help', 'rows' => 6, 'cols' => 50, 'data-original-title' => $model->getAttributeLabel('option4'), 'data-content' => $model->getAttributeDescription('option4'))); ?>
            </div>
            <div class="span2">
                <?php echo $form->textFieldRow($model, 'answer', array('class' => 'span3 popover-help', 'size' => 60, 'maxlength' => 60, 'data-original-title' => $model->getAttributeLabel('answer'), 'data-content' => $model->getAttributeDescription('answer'))); ?>
            </div>
            <div class="span2">
                <?php echo $form->textAreaRow($model, 'explanation', array('class' => 'span5 popover-help', 'rows' => 6, 'cols' => 50, 'data-original-title' => $model->getAttributeLabel('explanation'), 'data-content' => $model->getAttributeDescription('explanation'))); ?>
            </div>
        </div>
    </fieldset>

    <?php
    $this->widget(
        'bootstrap.widgets.TbButton', array(
            'type'        => 'primary',
            'encodeLabel' => false,
            'buttonType'  => 'submit',
            'label'       => '<i class="icon-search icon-white">&nbsp;</i> ' . Yii::t('question', 'Искать вопрос'),
        )
    ); ?>

<?php $this->endWidget(); ?>

protected/modules/question/views/default/create.php
<?php
/**
 * Отображение для create:
 *
 *   @category YupeView
 *   @package  YupeCMS
 *   @author   Yupe Team <team@yupe.ru>
 *   @license  https://github.com/yupe/yupe/blob/master/LICENSE BSD
 *   @link     http://yupe.ru
 **/
    $this->breadcrumbs = array(
        Yii::app()->getModule('question')->getCategory() => array(),
        Yii::t('question', 'Вопросы') => array('/question/default/index'),
        Yii::t('question', 'Добавление'),
    );

    $this->pageTitle = Yii::t('question', 'Вопросы - добавление');

    $this->menu = array(
        array('icon' => 'list-alt', 'label' => Yii::t('question', 'Управление вопросами'), 'url' => array('/question/default/index')),
        array('icon' => 'plus-sign', 'label' => Yii::t('question', 'Добавить вопрос'), 'url' => array('/question/default/create')),
    );
?>
<div class="page-header">
    <h1>
        <?php echo Yii::t('question', 'Вопросы'); ?>
        <small><?php echo Yii::t('question', 'добавление'); ?></small>
    </h1>
</div>

<?php echo $this->renderPartial('_form', array('model' => $model)); ?>

protected/modules/question/views/default/index.php
<?php
/**
 * Отображение для index:
 *
 * @category YupeView
 * @package  YupeCMS
 * @author   Yupe Team <team@yupe.ru>
 * @license  https://github.com/yupe/yupe/blob/master/LICENSE BSD
 * @link     http://yupe.ru
 **/
$this->breadcrumbs = array(
	Yii::app()->getModule('question')->getCategory() => array(),
	Yii::t('question', 'Вопросы')                    => array('/question/default/index'),
	Yii::t('question', 'Управление'),
);

$this->pageTitle = Yii::t('question', 'Вопросы - управление');

$this->menu = array(
	array('icon' => 'list-alt', 'label' => Yii::t('question', 'Управление вопросами'), 'url' => array('/question/default/index')),
	array('icon' => 'plus-sign', 'label' => Yii::t('question', 'Добавить вопрос'), 'url' => array('/question/default/create')),
);
?>
<div class="page-header">
	<h1>
		<?php echo Yii::t('question', 'Вопросы'); ?>
		<small><?php echo Yii::t('question', 'управление'); ?></small>
	</h1>
</div>

<p> <?php echo Yii::t('question', 'В данном разделе представлены средства управления вопросами'); ?>
</p>

<?php
$this->widget('application.modules.yupe.components.YCustomGridView', array(
	'id'           => 'question-grid',
	'type'         => 'condensed',
	'dataProvider' => $model->search(),
	'filter'       => $model,
	'columns'      => array(
		array(
			'name'        => 'id',
			'type'        => 'raw',
			'value'       => 'CHtml::link($data->id, array("/question/default/update", "id" => $data->id))',
			'htmlOptions' => array('width' => '50px'),
		),
		array(
			'name'   => 'theme_id',
			'value'  => '$data->getThemeName()',
			'filter' => CHtml::listData($this->module->getThemeList(), 'id', 'name'),
			'htmlOptions' => array('width' => '170px'),
		),
		array(
			'name'  => 'text',
			'type'  => 'raw',
			'value' => '$data->text',
		),
		array(
			'class'       => 'bootstrap.widgets.TbButtonColumn',
			'htmlOptions' => array('width' => '70px'),
		),
	),
)); ?>

protected/modules/question/views/default/update.php
<?php
/**
 * Отображение для update:
 *
 *   @category YupeView
 *   @package  YupeCMS
 *   @author   Yupe Team <team@yupe.ru>
 *   @license  https://github.com/yupe/yupe/blob/master/LICENSE BSD
 *   @link     http://yupe.ru
 **/
    $this->breadcrumbs = array(
        Yii::app()->getModule('question')->getCategory() => array(),
        Yii::t('question', 'Вопросы') => array('/question/default/index'),
        $model->id => array('/question/default/view', 'id' => $model->id),
        Yii::t('question', 'Редактирование'),
    );

    $this->pageTitle = Yii::t('question', 'Вопросы - редактирование');

    $this->menu = array(
        array('icon' => 'list-alt', 'label' => Yii::t('question', 'Управление вопросами'), 'url' => array('/question/default/index')),
        array('icon' => 'plus-sign', 'label' => Yii::t('question', 'Добавить вопрос'), 'url' => array('/question/default/create')),
        array('label' => Yii::t('question', 'Вопрос') . ' «' . mb_substr($model->id, 0, 32) . '»'),
        array('icon' => 'pencil', 'label' => Yii::t('question', 'Редактирование вопроса'), 'url' => array(
            '/question/default/update',
            'id' => $model->id
        )),
        array('icon' => 'eye-open', 'label' => Yii::t('question', 'Просмотреть вопрос'), 'url' => array(
            '/question/default/view',
            'id' => $model->id
        )),
        array('icon' => 'trash', 'label' => Yii::t('question', 'Удалить вопрос'), 'url' => '#', 'linkOptions' => array(
            'submit' => array('/question/default/delete', 'id' => $model->id),
            'confirm' => Yii::t('question', 'Вы уверены, что хотите удалить вопрос?'),
        )),
    );
?>
<div class="page-header">
    <h1>
        <?php echo Yii::t('question', 'Редактирование') . ' ' . Yii::t('question', 'вопроса'); ?><br />
        <small>&laquo;<?php echo $model->id; ?>&raquo;</small>
    </h1>
</div>

<?php echo $this->renderPartial('_form', array('model' => $model)); ?>

protected/modules/question/views/default/view.php
<?php
/**
 * Отображение для view:
 *
 * @category YupeView
 * @package  YupeCMS
 * @author   Yupe Team <team@yupe.ru>
 * @license  https://github.com/yupe/yupe/blob/master/LICENSE BSD
 * @link     http://yupe.ru
 **/

/* @var $model Question */
$this->breadcrumbs = array(
	Yii::app()->getModule('question')->getCategory() => array(),
	Yii::t('question', 'Вопросы')                    => array('/question/default/index'),
	$model->id,
);

$this->pageTitle = Yii::t('question', 'Вопросы - просмотр');

$this->menu = array(
	array('icon' => 'list-alt', 'label' => Yii::t('question', 'Управление вопросами'), 'url' => array('/question/default/index')),
	array('icon' => 'plus-sign', 'label' => Yii::t('question', 'Добавить вопрос'), 'url' => array('/question/default/create')),
	array('label' => Yii::t('question', 'Вопрос') . ' «' . mb_substr($model->id, 0, 32) . '»'),
	array('icon' => 'pencil', 'label' => Yii::t('question', 'Редактирование вопроса'), 'url' => array(
		'/question/default/update',
		'id' => $model->id
	)),
	array('icon' => 'eye-open', 'label' => Yii::t('question', 'Просмотреть вопрос'), 'url' => array(
		'/question/default/view',
		'id' => $model->id
	)),
	array('icon' => 'trash', 'label' => Yii::t('question', 'Удалить вопрос'), 'url' => '#', 'linkOptions' => array(
		'submit'  => array('/question/default/delete', 'id' => $model->id),
		'confirm' => Yii::t('question', 'Вы уверены, что хотите удалить вопрос?'),
	)),
);
?>
<div class="page-header">
	<h1>
		<?php echo Yii::t('question', 'Просмотр') . ' ' . Yii::t('question', 'вопроса'); ?><br />
		<small>&laquo;<?php echo $model->id; ?>&raquo;</small>
	</h1>
</div>

<?php $this->widget('bootstrap.widgets.TbDetailView', array(
	'data'       => $model,
	'attributes' => array(
		'id',
		array(
			'name'  => 'theme_id',
			'type'  => 'raw',
			'value' => CHtml::link($model->getThemeName(), array('/questiontheme/default/update', 'id' => $model->theme_id)),
		),
		array(
			'name' => 'text',
			'type' => 'raw',
		),
		'option1',
		'option2',
		'option3',
		'option4',
		array(
			'name'  => 'answer',
			'value' => $model->getAnswerName(),
		),
		'explanation',
	),
)); ?>